baseURL = "https://ryansydnor.com/"
languageCode = "en-us"
title = "Technologist"

[Params]
    author = "Ryan Sydnor"
    description = "Ryan Sydnor - Technologist based in NYC"
    logoBig = "Ryan Sydnor"
    logoSmall = "RS"
    dateform = "Jan 2 2006"
    twitter = "rtsydnor"
    linkedin = "ryansydnor"
    github = "ryansydnor"
    email = "ryan.t.sydnor@gmail.com"
    googleAnalytics = "UA-116295220-1"
    highlightJS = true
    copyright = false
    credit = false
    favicon = true
    DisqusShortname = "ryansydnor"

[[menu.main]]
    name = "Projects"
    url  = "/#projects"
    weight = 1
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 2
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 3